version: '3'
services:
  elasticsearch:
    image: "elasticsearch:5"
    networks:
      - frontend
    restart: always
    volumes:
      - ./Elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock = true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  bobcat_search:
    image: "bjdix/bobcat_search:1.0.0"
    networks:
      - frontend
    restart: always
    ports:
      - "8005:8005"

networks:
  frontend: