version: '3'
services:
  elasticsearch:
    image: "elasticsearch:5"
    networks:
      - frontend
    restart: always
    volumes:
      - ./Elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock = true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
      retries: 6

  bobcat_search:
    image: "bjdix/bobcat_search:1.0.0"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - frontend
    restart: always
    ports:
      - "8005:8005"

networks:
  frontend: